name: fragnet-merges
channels:
- conda-forge
- schrodinger
dependencies:
- pip=21.1.1
- rdkit=2021.09.4
- scipy=1.8.1
- pymol=2.5.2
- pip:
  - im-data-manager-job-utilities==1.0.1
  - pebble==4.6.3
  - neo4j==4.4.0
